name: Build
on: push
jobs:
  build:
    name: Build for Raspberry Pi 3B(+)
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run Bazel build
        uses: ttiurani/bazel-action@develop
        with:
          command: 'build //:hello --platforms //:arm64-linux --crosstool_top=//cc_toolchains/aarch64-rpi3-linux-gnu:gcc_toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=aarch64 --incompatible_enable_cc_toolchain_resolution'
      - uses: actions/upload-artifact@v3
        with:
          name: hello-for-rasp
          path: bazel-bi*/hello
